### ISSUE TITLE
Support for Helm 3

### ISSUE THREAD

**Issue by chowarth123** [IBM/kubernetes-driver#10]
**Problem:** error when trying to install packages against a helm 3 environment.

**Error seen:**
`
Helm install failed: b\'Error: parse error in "<template>": template: <template>:<line>: function "<function>" not defined\\n\''
`

**Steps to reproduce:** deploy helm chart via ALM using Brent resource manager with Kubernetes Driver. The Helm chart works manually from command line using helm on the Helm 3 environment

There have been a number of changes between Helm 2 and 3: https://helm.sh/docs/faq/#changes-since-helm-2. The changes may be causing issues.

**Proposed solution:** We should be able to update the dockerfile line:
`ENV SUPPORTED_HELM_VERSIONS ${SUPPORTED_HELM_VERSIONS:-2.8.2 2.16.7}`
Adding a Helm 3 version to it and rebuild the docker image then when creating a deployment location set the `helm.version` property to use the 3.x version

**Comment by dvaccarosenna** [comment]
Fixed by PR #12
