### ISSUE TITLE
Where can readiness check logs be seen? 

### ISSUE THREAD

**Issue by mudverma** [IBM/kubernetes-driver#39]
I have a simple readiness script that logs some variables. Where can I see that logged? 

```
def checkReady(keg, props, resultBuilder, log, *args, **kwargs):
    log.entry("keg")
    log.entry(keg)
    log.entry("pros")
    log.entry(props)
    return resultBuilder.notReady()
```

kubectl logs kubedriver-* doesn't show them. Where are these logs being printed? 

reference: https://github.com/IBM/kubernetes-driver/blob/master/docs/user-guide/ready-checks.md#log

**Comment by dvaccarosenna** [comment]
Hi @mudverma, it's probably not clear enough in the docs (so we should update them) but these log entries only appear in the kubedriver pod logs in 2 cases: 
- When the Kubedriver log level is set to DEBUG (default is INFO) 
- When the checkReady script experiences an error

You can increase the log level to DEBUG by modifying the configmap named `kubedriver-env`:

```
oc edit configmap kubedriver-env
```

Change the `LOG_LEVEL` setting:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedriver-env
data:
  ...
  "LOG_LEVEL": "DEBUG"
  ...
```

Then restart the kubedriver pod (scale it to 0 or delete it, a new pod will be automatically created)

```
oc delete pod kubedriver-xyz
```

**Comment by mudverma** [comment]
Thank You @dvaccarosenna  This helps.
