### ISSUE TITLE
Unable to access driver's swagger UI

### ISSUE THREAD

**Issue by aviweit** [IBM/kubernetes-driver#5]
I can not access swagger UI under the path api/resourcedriver/ui (as instructed in https://github.com/accanto-systems/kubernetes-driver/blob/0.0.3/docs/install.md)

However, path api/driver/ui/ works for me.

Thanks.

**Comment by dvaccarosenna** [comment]
Ah, ok. Certainly a typo in the docs. Thanks for letting us know.
